In [15]:
import numpy as np

rows = 6
col = 4

# below, generate matrices of integers, bounds [0,9), size 4 x 6 (R x C)
A = np.random.randint(10,size=(col, rows))
B = np.random.randint(10,size=(col, rows))

print('A:\n' + str(A))
print(' ')
print('B:\n' + str(B))
print(' ')

dps = np.zeros(6)  # dps : [0., 0., 0., 0., 0., 0.]
for i in range(6):
    dps[i] = np.dot(A[:, i], B[:, i]) # traverse all columns
    print(f'The dot product between column {i+1} is: {dps}')

print(' ')
print(dps)

A:
[[8 8 0 3 9 3]
 [7 8 3 0 0 8]
 [6 6 0 3 4 1]
 [4 9 6 5 4 4]]
 
B:
[[1 0 0 0 3 9]
 [1 8 0 6 2 9]
 [1 8 6 7 3 3]
 [4 6 8 9 1 2]]
 
The dot product between column 1 is: [37.  0.  0.  0.  0.  0.]
The dot product between column 2 is: [ 37. 166.   0.   0.   0.   0.]
The dot product between column 3 is: [ 37. 166.  48.   0.   0.   0.]
The dot product between column 4 is: [ 37. 166.  48.  66.   0.   0.]
The dot product between column 5 is: [ 37. 166.  48.  66.  43.   0.]
The dot product between column 6 is: [ 37. 166.  48.  66.  43. 110.]
 
[ 37. 166.  48.  66.  43. 110.]
