In [3]:
import numpy as np

# Explore whether the trace is linear

# tr(A) + tr(B) == tr(A + B) ?
# tr(l*A) == l*tr(A)

m = 4
n = 4

A = np.random.randint(10, size=(m, n))
B = np.random.randint(10, size=(m, n))
print(A), print(' ')
print(B), print(' ')

l = np.random.randint(0, 10)
print(l), print(' ')

print('tr(A+B) = ' + str(np.trace(A + B)))
print('tr(A)+tr(B) = ' + str(np.trace(A) + np.trace(B)))

print(' ')

print('tr(l*A) = ' + str(np.trace(l * A)))
print('l*tr(A) = ' + str(l * np.trace(A)))

[[3 4 4 0]
 [2 0 6 0]
 [7 4 1 7]
 [0 6 0 4]]
 
[[0 7 0 6]
 [0 8 1 1]
 [2 0 9 6]
 [7 2 7 1]]
 
5
 
tr(A+B) = 26
tr(A)+tr(B) = 26
 
tr(l*A) = 40
l*tr(A) = 40
