In [2]:
import numpy as np

# Is matrix-scalar multiplication a linear operation ?

# matrix sizes
m = 7
n = 5

# create two matrices
A = np.random.randint(10, size=(m,n))
B = np.random.randint(10, size=(m,n))

# scalar
s = np.random.randint(0, 10)

# compute both sides of the equation
result_L = s * (A+B)
result_R = s*A + s*B

print(result_L), print(' ')
print(result_R), print(' ')

print(result_L - result_R)

[[117  90  90 108  54]
 [ 72 117 117  45 117]
 [ 36   0   9   0  36]
 [ 27  90 144  45  90]
 [  9 108  18  99   0]
 [ 72 108 126  81 126]
 [ 72 117  99  90  99]]
 
[[117  90  90 108  54]
 [ 72 117 117  45 117]
 [ 36   0   9   0  36]
 [ 27  90 144  45  90]
 [  9 108  18  99   0]
 [ 72 108 126  81 126]
 [ 72 117  99  90  99]]
 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
