In [4]:
import numpy as np

## the additive method

# declare sizes
m = n = 5

# create matrices
A = np.random.randint(10, size=(m, n))
S = (A + A.T) / 2

# Assumption that S-S^T should be 0, if so, S is symmetric
print(S - S.T)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5 5 6]
 [8 2 0]
 [8 5 5]
 [4 2 3]
 [6 9 3]]


In [8]:
## the multiplicative method

# declare sizes
m = 5
n = 3

# create matrices
A = np.random.randint(10, size=(m, n))

# below, A_t stands for A transposed
A_tA = A.T @ A
AA_t = A @ A.T

# show that the matrices are square
print(A_tA.shape), print(' ')
print(AA_t.shape), print(' ')

# show that the matrices are symmetric
print(AA_t - AA_t.T), print(' ')
print(A_tA - A_tA.T), print(' ')

(3, 3)
 
(5, 5)
 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
 


(None, None)