In [3]:
import numpy as np

# declare matrix sizes
m = 10
n = 2

# create the matrices
A = np.random.randint(10, size=(m, n))
B = np.random.randint(10, size=(m, n))

print(A), print(' ')
print(B), print(' ')

# Note: difference between matrix multiplication (using '@')
C1 = np.multiply(A, B)
C2 = A * B

print(C1), print(' ')
print(C2), print(' ')
print(C1 - C2)

[[6 8]
 [3 5]
 [3 1]
 [9 8]
 [8 2]
 [8 2]
 [8 6]
 [7 1]
 [1 2]
 [7 3]]
 
[[4 0]
 [4 9]
 [1 5]
 [4 7]
 [6 3]
 [3 0]
 [8 9]
 [6 7]
 [9 9]
 [1 2]]
 
[[24  0]
 [12 45]
 [ 3  5]
 [36 56]
 [48  6]
 [24  0]
 [64 54]
 [42  7]
 [ 9 18]
 [ 7  6]]
 
[[24  0]
 [12 45]
 [ 3  5]
 [36 56]
 [48  6]
 [24  0]
 [64 54]
 [42  7]
 [ 9 18]
 [ 7  6]]
 
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
