In [6]:
import numpy as np

# generate two matrices
m = 4
n = 6

A = np.random.randint(10, size=(m,n))
B = np.random.randint(10, size=(n,m))

# build the product matrix layer-wise
C1 = np.zeros((m,m))
for i in range(n):
    C1 += np.outer(A[:,i], B[i,:])

print(C1), print(' ')
# implement matrix multiplication
C2 = A@B
print(C2), print(' ')

# compare results
print(C1-C2)

[[117. 115. 160. 152.]
 [ 67.  47.  73.  81.]
 [166.  91. 131. 174.]
 [ 81. 109.  97. 105.]]
 
[[117 115 160 152]
 [ 67  47  73  81]
 [166  91 131 174]
 [ 81 109  97 105]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
