In [4]:
import numpy as np

# number of elements
m = 4

# create matrices
N = np.random.randint(-10, 11, (m, m))
S = np.round(N.T * N / m ** 2)  # scaled symmetric

print(N), print(' ')
print(S), print(' ')

# create a vector
w = np.array([-1, 0, 1, 2])

# multiply vector with S (symmetric matrix)
print(S @ w)
print(S.T @ w)
print(w @ S)
print(w.T @ S.T)
print(w.T @ S)

print(' ')
# multiply vector with N (non-symmetric matrix)
print(N @ w)
print(N.T @ w)
print(w @ N)
print(w.T @ N.T)
print(w.T @ N)

[[ -7   9  -6  10]
 [ 10  -3   7  -2]
 [ -8 -10   5   5]
 [ -4  -5  -5 -10]]
 
[[ 3.  6.  3. -2.]
 [ 6.  1. -4.  1.]
 [ 3. -4.  2. -2.]
 [-2.  1. -2.  6.]]
 
[-4. -8. -5. 12.]
[-4. -8. -5. 12.]
[-4. -8. -5. 12.]
[-4. -8. -5. 12.]
[-4. -8. -5. 12.]
 
[ 21  -7  23 -21]
[ -9 -29   1 -25]
[ -9 -29   1 -25]
[ 21  -7  23 -21]
[ -9 -29   1 -25]
