In [2]:
import numpy as np

n = 2
L = np.random.randint(10,size=(n,n))
I = np.random.randint(10,size=(n,n))
V = np.random.randint(10,size=(n,n))
E = np.random.randint(10,size=(n,n))

# result of 'forward' multiplication and then transpose
res1 = np.matrix.transpose(L @ I @ V @ E)
print(res1), print(' ')
# result of 'flipped/backwards ' multiplication of transposed matrices
res2 = E.T @ V.T @ I.T @ L.T
print(res2), print(' ')

# test for equality
print(res1 - res2)

[[5176 7164]
 [1696 2256]]
 
[[5176 7164]
 [1696 2256]]
 
[[0 0]
 [0 0]]
