In [9]:
import numpy as np

v1 = np.array([1,3,2])
v2 = np.array([-1,0,1])

# outer product
outer_product_1 = np.outer(v1, v2) # simplified version (matrix of ints)

outer_product_2 = np.zeros((len(v1), len(v1))) # detailed version (matrix of floats)
for i in range(0, len(v1)):
    for j in range(0, len(v2)):
        outer_product_2[i, j] = v1[i] * v2[j]

print(outer_product_1)
print(' ')
print(outer_product_2)

[[-1  0  1]
 [-3  0  3]
 [-2  0  2]]
 
[[-1.  0.  1.]
 [-3.  0.  3.]
 [-2.  0.  2.]]
