In [3]:
import numpy as np

# create random matrices
A = np.random.randint(10, size=(5,4))
B = np.random.randint(10, size=(5,4))
C = np.random.randint(10, size=(5,4))
print(A), print(' '), print(B), print(' '), print(C), print(' ')

# Addition
print(A+B), print(' ')
print(A+C), print(' ')

# Shifting a matrix
l = .3 # lambda (Scalar)
N = 5 # matrix size
D = np.random.randint(10, size=(N,N))

D_shifted = D + l*np.eye(N)
print(D), print(' '), print(D_shifted)

[[7 2 0 6]
 [6 6 3 5]
 [2 6 6 1]
 [2 6 9 9]
 [6 7 7 3]]
 
[[8 5 8 4]
 [0 8 8 9]
 [2 8 9 3]
 [7 0 9 0]
 [6 2 0 3]]
 
[[9 8 9 9]
 [6 2 5 4]
 [6 5 5 0]
 [1 5 7 0]
 [5 5 6 6]]
 
[[15  7  8 10]
 [ 6 14 11 14]
 [ 4 14 15  4]
 [ 9  6 18  9]
 [12  9  7  6]]
 
[[16 10  9 15]
 [12  8  8  9]
 [ 8 11 11  1]
 [ 3 11 16  9]
 [11 12 13  9]]
 
[[8 5 6 9 8]
 [7 3 5 3 9]
 [9 1 2 5 6]
 [1 6 5 1 8]
 [5 4 3 3 5]]
 
[[8.3 5.  6.  9.  8. ]
 [7.  3.3 5.  3.  9. ]
 [9.  1.  2.3 5.  6. ]
 [1.  6.  5.  1.3 8. ]
 [5.  4.  3.  3.  5.3]]


(None, None, None)