In [2]:
import numpy as np

# create a matrix
# create a vector with values [1,13) and reshape it as a matrix 3x4
A = np.reshape(np.arange(1, 13), (3, 4), 'F')  # F = column, C = row

# create two 'vectors'
r = [10,20,30,40]
c = [100,200,300]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ')

# broadcast on the rows (works natively)
print(A+r), print(' ')

# broadcast on the columns (reshape c to be a 3x1 matrix or 3D vector
print(A+np.reshape(c,(len(c),1)))

# print

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 
[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
