In [3]:
import numpy as np

scalar = 5
M = np.round(scalar * np.random.randint(10, size=(4, 4)))
print(M), print(' ')

# extract the diagonals
d = np.diag(M)  # matrix as input, output as vector
D = np.diag(d)  # vector as input, output as matrix
print(d), print(' ')
print(D), print(' ')

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum(np.diag(M))
print(tr, tr2)

[[25 25 15 20]
 [ 5 45 40  5]
 [35 10 20 15]
 [40 25 40  0]]
 
[25 45 20  0]
 
[[25  0  0  0]
 [ 0 45  0  0]
 [ 0  0 20  0]
 [ 0  0  0  0]]
 
90 90
