In [9]:
import numpy as np

# square(5x5) vs rectangular(5x2)
S = np.random.randint(10, size=(5, 5))
R = np.random.randint(10, size=(5, 2))
print(S), print(' ')
print(R), print(' ')

# Identity matrix (M for input)
I = np.eye(3)
print(I), print(' ')

# Zeros matrix (tuple for input)
Z = np.zeros((4, 4))
print(Z), print(' ')

# Diagonal matrix (list or np array for input)
# Python will position the input elements on the diagonal of the matrix
D = np.diag([1, 2, 3, 5, 2])
print(D), print(' ')

# Triangular matrix
S = np.random.randint(10, size=(5, 5))
U = np.triu(S)  # upper triangular matrix
L = np.tril(S)  # lower triangular matrix
print(U), print(' '), print(L), print(' ')

# Concatenate matrices
A = np.random.randint(10, size=(3,2))
B = np.random.randint(10, size=(3,5))
C = np.concatenate((A,B), axis=1)
print(C), print(' ')

[[7 7 2 7 5]
 [4 7 5 6 2]
 [1 4 6 9 0]
 [7 6 3 7 6]
 [8 1 0 2 4]]
 
[[0 4]
 [7 7]
 [2 6]
 [7 6]
 [9 0]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[4 8 4 8 4]
 [0 9 3 1 1]
 [0 0 9 8 1]
 [0 0 0 6 7]
 [0 0 0 0 3]]
 
[[4 0 0 0 0]
 [6 9 0 0 0]
 [1 4 9 0 0]
 [6 7 3 6 0]
 [5 3 4 5 3]]
 
[[6 3 6 6 6 7 4]
 [2 3 1 8 0 2 2]
 [0 9 7 7 6 0 0]]
 


(None, None)