In [11]:
import numpy as np

M = np.array([[1, 2, 3],
              [2, 3, 4]])

print(M), print(' ')
print(M.T), print(' ')  # one transposition
print(M.T.T), print(' ')  # double-transposition, returns the original matrix

# using the transpose function
print(np.transpose(M)), print(' ')

# complex matrices
C = np.array([[4+1j,
              3,
              2-4j]], dtype=complex)

print(C), print(' ')
print(C.T), print(' ')
print(np.transpose(C)), print(' ')

# hermitian transpose (flipped signs)
print(np.matrix(C).H)

[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[4.+1.j 3.+0.j 2.-4.j]]
 
[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]
 
[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]
 
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
