In [3]:
import numpy as np

# create two square matrices: "full" and diagonal
m = 4
A = np.random.randint(10, size=(m,m))
D = np.diag(np.random.randint(10, size=m))

print(A), print(' ')
print(D), print(' ')

# multiply each matrix by itself (standard and hadamard)
print(A@A), print(' ')
print(A*A), print(' ')

print(D@D), print(' ')
print(D*D), print(' ')

[[6 2 9 1]
 [6 3 0 3]
 [5 5 8 2]
 [9 0 7 1]]
 
[[7 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
 
[[102  63 133  31]
 [ 81  21  75  18]
 [118  65 123  38]
 [ 98  53 144  24]]
 
[[36  4 81  1]
 [36  9  0  9]
 [25 25 64  4]
 [81  0 49  1]]
 
[[49  0  0  0]
 [ 0  9  0  0]
 [ 0  0 16  0]
 [ 0  0  0 49]]
 
[[49  0  0  0]
 [ 0  9  0  0]
 [ 0  0 16  0]
 [ 0  0  0 49]]
 


(None, None)