In [2]:
import numpy as np

# create two symmetric matrices
m = 3
A = np.random.randint(10, size=(m, m))
A_tA = A.T @ A

print(A), print(' ')

B = np.random.randint(10, size=(m, m))
B_tB = B.T @ B

print(B), print(' ')

# compute sum, multiplication and Hadamard multiplication
Cs = A_tA + B_tB
Cm = A_tA @ B_tB
Ch = A_tA * B_tB

# determine whether the result is symmetric
print(Cs - Cs.T), print(' ')
print(Cm - Cm.T), print(' ')
print(Ch - Ch.T)

[[4 0 6]
 [8 8 3]
 [4 7 9]]
 
[[2 6 8]
 [8 2 6]
 [5 9 7]]
 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
 
[[    0  3054  6699]
 [-3054     0  3813]
 [-6699 -3813     0]]
 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
