In [1]:
import numpy as np
from sympy import *

# make some random matrices (convert np matrix to sympy matrix)
A = Matrix(np.random.randn(4,4))
B = Matrix(np.random.randn(4,3))

# compute R.R.E.F
rrefA = A.rref()
rrefB = B.rref()

# print the matrices and their respective rrefs
print(np.array(rrefA[0]))
print(' ')
print(np.array(rrefB[0]))


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [3]:
# RREF of different (random) matrices
# - square
# - rectangular (tall,wide)
# - linear dependencies (on C, on R)

# square
m = n = 5
A = np.random.randint(10, size=(m, n))

# add linear dependency (C1 = C2)
A[:, 0] = A[:, 1]
print(np.array(Matrix(A).rref()[0]))

[[0 7 6 3 2]
 [1 3 9 0 1]
 [2 2 4 0 1]
 [9 1 8 8 7]
 [8 9 0 0 4]]
[[7 7 6 3 2]
 [3 3 9 0 1]
 [2 2 4 0 1]
 [1 1 8 8 7]
 [9 9 0 0 4]]
[[1 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
