In [5]:
import numpy as np

# matrix size
m = 30

# create square symmetric matrix
A = np.random.randn(m, m)
A = np.round(10 * A.T @ A)
print(A), print('-----------------')
# reduce matrix rank (set C0 = C1)
A[:, 0] = A[:, 1]
print(A)
# shift amount/weight (l = lambda)
l = .01

# resulting matrix
B = A + l * np.eye(m, m)

# display info
print('rank(w/o shifting) = %d' % np.linalg.matrix_rank(A))
print('rank(with shifting) = %d' % np.linalg.matrix_rank(B))

[[ 71.  27.  48. -10.]
 [ 27.  30. -24. -14.]
 [ 48. -24. 181.  23.]
 [-10. -14.  23.   8.]]
-----------------
[[ 27.  27.  48. -10.]
 [ 30.  30. -24. -14.]
 [-24. -24. 181.  23.]
 [-14. -14.  23.   8.]]
rank(w/o shifting) = 3
rank(with shifting) = 4
