In [19]:
import numpy as np

m = 14
n = 3

# create matrices
A = np.random.randint(10, size=(m,n))

A_tA = np.transpose(A) @ A
AA_t = A @ np.transpose(A)
nl_and_tab = '\n\t'
print(f'A_tA:   {A_tA[0]}{nl_and_tab}{A_tA[1]}{nl_and_tab}{A_tA[2]}, rank={np.linalg.matrix_rank(A_tA)}'), print(' ')
print(f'AA_t:   {AA_t[0]}{nl_and_tab}{AA_t[1]}{nl_and_tab}{AA_t[2]}, rank={np.linalg.matrix_rank(AA_t)}')

A_tA:   [436 356 203]
	[356 619 334]
	[203 334 281], rank=3
 
AA_t:   [117  93  15 123  60 102 108  84  48  24  99  75  39  78]
	[ 93 155  75  98  92 108 105 111 111  74 132 104  40 142]
	[15 75 51 16 42 34 29 45 63 46 54 44 12 72], rank=3
