In [13]:
# Problem: determine whether the following vector 'v' is in the span of the sets S,T
import numpy as np

# declare vector
v = np.array([[1,2,3,4]]).T # transpose
print(v), print(' ')

# declare sets S and T and convert them to matrices
S = np.vstack(([4,3,6,2], [0,4,0,1])).T
T = np.vstack(([1,2,2,2], [0,0,1,2])).T

print(S),print(' ')
print(T),print(' ')

Sv = np.concatenate((S,v), axis=1)
Tv = np.concatenate((T,v), axis=1)

print(Sv),print(' ')
print(Tv),print(' ')
print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

# Notes:
# To determine whether a vector is in the span of a set, we concatenate the vector to the set's vector
# matrices and observe any changes in the rank, if the rank increases, the vector is NOT within the span
# of the set,otherwise, it is.
#
# As it can be seen, the rank of Sv has changed to 3 (previously 2, it adds new information to the matrix),
# hence v is not in the span of set S.
# Tv has a rank of 2 still as C3 (v) can be defined as C1+C2, hence v is in the span of set T (v does not
# add new information to the matrix T).


[[1]
 [2]
 [3]
 [4]]
 
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
 
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
 
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
 
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
 
3
2
